name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag build-with-ffmpeg-image:$(date +%s)
    - name: Push to GitHub Registry
      run: docker push ghcr.io/dipaolo/build-with-ffmpeg-image:latest
